
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-gauchoride-m23-9am-2
owner: ucsb-cs156-m23
repo_name: proj-gauchoride-m23-9am-2
pull_requests: [{"author":{"id":"U_kgDOBtFRUg","is_bot":false,"login":"Mohamed-Elfouly","name":""},"headRefName":"Mohamed-User-CellPages","number":22,"title":"Mohamed user cell pages","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/22"},{"author":{"id":"U_kgDOBtFRUg","is_bot":false,"login":"Mohamed-Elfouly","name":""},"headRefName":"Mohamed-User-CellController","number":20,"title":"Mohamed userProfile (cellPhone) controller","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/20"},{"author":{"id":"U_kgDOBtFRUg","is_bot":false,"login":"Mohamed-Elfouly","name":""},"headRefName":"Mohamed-User-CellEntity","number":18,"title":"Adds a string cellPhone","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/18"}]
