
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-gauchoride-m23-9am-2
owner: ucsb-cs156-m23
repo_name: proj-gauchoride-m23-9am-2
pull_requests: [{"author":{"id":"U_kgDOBh3juQ","is_bot":false,"login":"andrewthaii","name":""},"headRefName":"Andrew-RiderApplication-Entity","number":46,"title":"Andrew rider application entity","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/46"},{"author":{"id":"U_kgDOBh3juQ","is_bot":false,"login":"andrewthaii","name":""},"headRefName":"Andrew-RiderDashboard-table","number":42,"title":"Andrew rider dashboard table","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/42"},{"author":{"id":"MDQ6VXNlcjM5ODM3OTM5","is_bot":false,"login":"cjyu81","name":"Charlie"},"headRefName":"Charlie-ShiftCRUD-CreatePage","number":40,"title":"Charlie shift crud create page","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/40"},{"author":{"id":"U_kgDOBh3juQ","is_bot":false,"login":"andrewthaii","name":""},"headRefName":"Andrew-RiderDashboard-Placeholder","number":37,"title":"Andrew rider dashboard placeholder","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/37"},{"author":{"id":"U_kgDOBtFRUg","is_bot":false,"login":"Mohamed-Elfouly","name":""},"headRefName":"Mohamed-ChatMessage-CRUD","number":33,"title":"Mohamed chat message CRUD","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/33"},{"author":{"id":"U_kgDOBtFRUg","is_bot":false,"login":"Mohamed-Elfouly","name":""},"headRefName":"Mohamed-User-CellPages","number":22,"title":"Mohamed user cell pages","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/22"}]
