
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-gauchoride-m23-9am-2
owner: ucsb-cs156-m23
repo_name: proj-gauchoride-m23-9am-2
pull_requests: [{"author":{"id":"U_kgDOBtFRUg","is_bot":false,"login":"Mohamed-Elfouly","name":""},"headRefName":"Mohamed-chatMessages-updated-create","number":78,"title":"Mohamed chat messages updated create","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/78"},{"author":{"id":"MDQ6VXNlcjM5ODM3OTM5","is_bot":false,"login":"cjyu81","name":"Charlie"},"headRefName":"Charlie-ShiftCRUD-EditPage","number":76,"title":"CRUD Operations for Driver Shift table","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/76"},{"author":{"id":"MDQ6VXNlcjgwNDMxNjE4","is_bot":false,"login":"abcdefucsb","name":"Shiyang/Bill"},"headRefName":"Bill-drivers-2","number":73,"title":"Bill Xin 2nd pr: Add a navbar element#64","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/73"},{"author":{"id":"U_kgDOBh3juQ","is_bot":false,"login":"andrewthaii","name":""},"headRefName":"Andrew-RiderApplication-Controller","number":72,"title":"Andrew rider application controller","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/72"},{"author":{"id":"MDQ6VXNlcjc3NzEwNDI2","is_bot":false,"login":"adityapatil834","name":"Aditya Patil"},"headRefName":"Addi-gauchoride1","number":70,"title":"Addi gauchoride1","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/pull/70"}]
